### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [ ]:
import numpy as np

original = np.random.randint(0,255,(3,28,28))
flat = original.reshape(1,3,28,28)
flatted = flat.flatten()

In [ ]:
original

array([[[161,  95,  11, ..., 194,  17,  98],
        [144, 174,  34, ..., 229, 252,  27],
        [236, 197,  36, ..., 145, 196,  27],
        ...,
        [243,  48, 233, ..., 207, 110, 135],
        [155, 108, 136, ...,  19, 190, 148],
        [157, 195, 189, ..., 198,  85,   3]],

       [[ 99, 156, 184, ..., 100,   7, 114],
        [207, 253, 132, ..., 242, 136, 155],
        [ 28, 205, 222, ...,  49, 147,  50],
        ...,
        [214, 175, 174, ..., 208, 108, 193],
        [ 73, 127,  13, ..., 150, 124,  88],
        [ 49,  88, 240, ..., 211,  14,  40]],

       [[ 72,  64, 152, ..., 249, 147,  50],
        [180,  34,  91, ...,  48,  16, 186],
        [222,  30, 218, ..., 193,  91, 254],
        ...,
        [191,  47, 219, ...,  18, 106, 210],
        [ 96,  59, 151, ...,  48,  27,  90],
        [151,  73, 193, ..., 216,  85,  40]]])

In [ ]:
flat

array([[[[161,  95,  11, ..., 194,  17,  98],
         [144, 174,  34, ..., 229, 252,  27],
         [236, 197,  36, ..., 145, 196,  27],
         ...,
         [243,  48, 233, ..., 207, 110, 135],
         [155, 108, 136, ...,  19, 190, 148],
         [157, 195, 189, ..., 198,  85,   3]],

        [[ 99, 156, 184, ..., 100,   7, 114],
         [207, 253, 132, ..., 242, 136, 155],
         [ 28, 205, 222, ...,  49, 147,  50],
         ...,
         [214, 175, 174, ..., 208, 108, 193],
         [ 73, 127,  13, ..., 150, 124,  88],
         [ 49,  88, 240, ..., 211,  14,  40]],

        [[ 72,  64, 152, ..., 249, 147,  50],
         [180,  34,  91, ...,  48,  16, 186],
         [222,  30, 218, ..., 193,  91, 254],
         ...,
         [191,  47, 219, ...,  18, 106, 210],
         [ 96,  59, 151, ...,  48,  27,  90],
         [151,  73, 193, ..., 216,  85,  40]]]])

In [ ]:
flatted

array([161,  95,  11, ..., 216,  85,  40])

### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [ ]:
print('Dimensions (original, flat, flatted):', original.ndim, flat.ndim, flatted.ndim)

Dimensions (original, flat, flatted): 3 4 1


In [ ]:
print('Memory addrs (original, flat, flatted):', '\n', original.data, '\n', flat.data, '\n', flatted.data)

Memory addrs (original, flat, flatted): 


In [ ]:
print('Shapes (original, flat, flatted):', '\n', original.shape, '\n', flat.shape, '\n', flatted.shape)

Shapes (original, flat, flatted): 
 (3, 28, 28) 
 (1, 3, 28, 28) 
 (2352,)


In [ ]:
print('Dtypes (original, flat, flatted):', '\n', original.dtype, '\n', flat.dtype, '\n', flatted.dtype)

Dtypes (original, flat, flatted): 
 int64 
 int64 
 int64


### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [ ]:
negative = np.negative(original)
negative

array([[[-161,  -95,  -11, ..., -194,  -17,  -98],
        [-144, -174,  -34, ..., -229, -252,  -27],
        [-236, -197,  -36, ..., -145, -196,  -27],
        ...,
        [-243,  -48, -233, ..., -207, -110, -135],
        [-155, -108, -136, ...,  -19, -190, -148],
        [-157, -195, -189, ..., -198,  -85,   -3]],

       [[ -99, -156, -184, ..., -100,   -7, -114],
        [-207, -253, -132, ..., -242, -136, -155],
        [ -28, -205, -222, ...,  -49, -147,  -50],
        ...,
        [-214, -175, -174, ..., -208, -108, -193],
        [ -73, -127,  -13, ..., -150, -124,  -88],
        [ -49,  -88, -240, ..., -211,  -14,  -40]],

       [[ -72,  -64, -152, ..., -249, -147,  -50],
        [-180,  -34,  -91, ...,  -48,  -16, -186],
        [-222,  -30, -218, ..., -193,  -91, -254],
        ...,
        [-191,  -47, -219, ...,  -18, -106, -210],
        [ -96,  -59, -151, ...,  -48,  -27,  -90],
        [-151,  -73, -193, ..., -216,  -85,  -40]]])

In [ ]:
sum = np.add(original, negative)
sum

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [ ]:
original[:,1,:10]

array([[144, 174,  34, 198, 218, 217,   9, 223, 135, 112],
       [207, 253, 132, 226, 188,  83,  61,  13,  29, 225],
       [180,  34,  91,  52,  21,   6, 236, 221,  63, 143]])

### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [ ]:
blue = original[2]
blue.shape

(28, 28)

In [ ]:
blue[0:3]

array([[ 72,  64, 152, 103, 105, 182,  92, 138,  93,  45, 195,  48,  58,
        174,  41, 164, 148, 215,  16, 171, 226, 128, 121, 247, 191, 249,
        147,  50],
       [180,  34,  91,  52,  21,   6, 236, 221,  63, 143, 206, 220, 176,
        128, 193, 219, 113,  18, 137, 214, 126, 125,  99, 168,  77,  48,
         16, 186],
       [222,  30, 218,  75, 175,  84,  68,  79, 220, 101, 159, 173, 206,
        157,  70,   6, 214,  67,  85,   0, 130, 193, 165, 150,  38, 193,
         91, 254]])

### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [ ]:
even = np.arange(100,step=2)
matrix = even.reshape(10,5)
print(matrix)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [ ]:
matrix.transpose()

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98]])

###Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [ ]:
for i in range(0,10):
  print( 'Mean of row ', i , ' ', np.mean(matrix[i], axis=0))

Mean of row  0   4.0
Mean of row  1   14.0
Mean of row  2   24.0
Mean of row  3   34.0
Mean of row  4   44.0
Mean of row  5   54.0
Mean of row  6   64.0
Mean of row  7   74.0
Mean of row  8   84.0
Mean of row  9   94.0

Mean of cols  [45. 47. 49. 51. 53.]


In [ ]:
print('Mean of cols', matrix.mean(axis=0))

Mean of cols [45. 47. 49. 51. 53.]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

We cannot create a 3x3 array with 50 elements. Since the 3x3 matrix contains only 9 elements. All values ​​with products of 50 and above can be used, with m*n being real numbers. For instance, m=1 and n=50;
m * n >= 50.